# Generated by Django 4.1 on 2022-09-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='threadHead',
            field=models.BooleanField(default=False),
        ),
    ]
