# Generated by Django 4.1 on 2022-09-28 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification_sent_post_threadhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_posted',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
