# Generated by Django 4.1 on 2022-09-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comments_time_posted_notification_time_notified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/posts/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(blank=True, default='media/cover_photo/default.jpeg', null=True, upload_to='media/cover_photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/profile_picture/default.jpg', null=True, upload_to='media/profile_picture/%Y/%m/%d'),
        ),
    ]
