# Generated by Django 4.1 on 2022-10-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_comments_media_remove_post_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='gif',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/posts/% Y/% m/% d'),
        ),
    ]
