# Generated by Django 4.1 on 2022-10-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_media_gif_alter_media_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/posts/%Y/%m/%d'),
        ),
    ]
