# Generated by Django 4.1 on 2022-10-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_media_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to='media/posts/gifs/%Y/%m/%d'),
        ),
    ]
