# Generated by Django 4.1 on 2022-10-11 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_media_gif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retweet',
            name='retweetId',
        ),
        migrations.RemoveField(
            model_name='retweet',
            name='text',
        ),
        migrations.RemoveField(
            model_name='retweet',
            name='thread',
        ),
        migrations.AddField(
            model_name='post',
            name='quoteId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_tweet', to='api.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweet_thread', to='api.post'),
        ),
    ]
