# Generated by Django 4.1 on 2022-10-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_retweet_retweetid_remove_retweet_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='retweetId',
        ),
        migrations.RemoveField(
            model_name='media',
            name='retweetId',
        ),
    ]
